version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:5001"
    env_file:
      - ./backend/.env

    networks:
      - fullstack-net
    restart: unless-stopped
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - fullstack-net
    depends_on:
      - backend
    restart: unless-stopped

networks:
  fullstack-net:
    driver: bridge
